language: android
jdk: oraclejdk8
android:
  components:
    - platform-tools
    - tools
    - build-tools-28.0.2
    - android-28
# Support library
    - extra-android-support
    - extra-android-m2repository

licenses:
    - 'android-sdk-license-.+'

before_script:
    - chmod +x gradlew

script:
   - chmod +x ./gradlew
   - ./gradlew assembleDebug assembleRelease
   - ./gradlew checkstyle
